x-depends-on-kafka-healthy: &depends_on_kafka_healthy
  kafka-broker:
    condition: service_healthy

services:
  kafka-broker:
    image: apache/kafka:4.1.1
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "${KAFKA_BROKER_PORT:-9092}:9092"
    environment:
      - PATH=/opt/kafka/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID:-8Zt6o8hOSRuY0rFBLv0BTA}
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9093,CONTROLLER://:9094,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9093,EXTERNAL://localhost:${KAFKA_BROKER_PORT:-9092}
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-broker:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test:
        - CMD-SHELL
        - bash -ec 'echo > /dev/tcp/127.0.0.1/9093'
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 60s

  schema-registry:
    image: confluentinc/cp-schema-registry:8.0.3
    platform: linux/amd64
    restart: unless-stopped
    depends_on: *depends_on_kafka_healthy
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-broker:9093

volumes:
  kafka_data:
